{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openrag-stack.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"  
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    # - host: {{ .Values.ingress.host }}
    - http:
        paths:
          {{- if .Values.ingress.paths.openrag.enabled }}
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: raycluster-head-svc
                port:
                  number: {{ .Values.env.config.RAY_SERVE_PORT }}
          {{- end }}
{{- end }}
